### ISSUE TITLE
Sign up to email/newsletter/CRM platform & import CSV

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#166] opened 2020-12-02 19:55 UTC
## 📋 Anything to add?

Dependency #165

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@jessicazartler

**Comment by tamarandom** [comment] 2021-02-05 17:38
Dupe of #197.

**Closed by tamarandom** 2021-02-05 17:38 UTC
Labels: Communications WG, Critical to Hatch, Next sprint?, OnboardingWG
