### ISSUE TITLE
Spotlight Demo/Speaker for TE Commons Weekly 

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#195] opened 2020-12-18 12:46 UTC
Hi! This is where @iviangita will find the project and presenters so that she can update our Weekly Agenda. 

Most helpful format is < project > by < presenter(s) >

- [x] March 4 - **Dacade** by Moritz Felipe and Paula Kuhn (confirmed by Eduardo) 
- [x] March 11 - **Token Kitchen** by Angela Kreitenweis (confirmed by Jess)
- [x] March 18 ARTDAO by Santig
- [x] March 25 Dashboard by Vitor 
- [ ] April 1
- [ ] April 8
- [ ] April 15

[Document for tracking the weekly presenters.
](https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0
)

**Comment by jessicazartler** [comment] 2021-01-06 18:35
Tracking here https://github.com/TECommons/coordination/issues/62
And here https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0

Need to ask about this -- would rather not have to make an issue for a 3rd route of tracking for this..

**Comment by tamarandom** [comment] 2021-01-07 08:19
Hey @jessicazartler, makes sense. #62 was the initialization of the process, it had more moving pieces while you were setting up the process. This is the the operation of making it happen each week. 🙏🏼

**Comment by jessicazartler** [comment] 2021-01-07 18:57
Awesome thank you! This week Jan. 7 we have Shawn "YGG" Anderson presenting on https://forum.tecommons.org/t/tec-labs-production-team-funding/201/2

Next. week Jan. 14 we have Shermin with Token Kitch (proposal to be done next week)

**Comment by jessicazartler** [comment] 2021-01-22 17:31
Still a little confused by repeating tasks -- are we using the same one over and over? Then they don't get closed?

The speaker for Jan. 28 is Govbase.. we have no one lined up after, I will ask Shermin to present in the fourth and asked the stewards for support in the telegram if needed

**Comment by freedumbs00** [comment] 2021-02-02 15:44
I as well would move this to Edaurdo

**Comment by jessicazartler** [comment] 2021-02-02 16:35
Messaged Angela to see if she wants to present Gitcoin Research group this week - will circle back

**Comment by markoprljic** [comment] 2021-02-02 16:39
Since we have this issue https://github.com/TECommons/coordination/issues/62 does that mean we can close this one?
@jessicazartler @tamarandom

**Comment by tamarandom** [comment] 2021-02-02 17:43
I see what happened. I accidentally reopened #62 because I didn't remove the #repeating label when I closed it. Fixed!! ;) 

This issue to to make sure that it gets done every week. It is a weekly repeating task. It should only have 1 owner so I'll untag @jessicazartler and let @eduardovegap consult her as needed.

**Comment by jessicazartler** [comment] 2021-02-02 17:49
Angela will present this week :D thanks @liviade for the idea!!!! And so we just need to find someone for next week @vegayp updated in curate sheet

**Comment by tamarandom** [comment] 2021-02-02 18:02
@jessicazartler @liviade1 : Pass, shoot, score!! 🙌🏼

**Comment by tamarandom** [comment] 2021-02-24 18:18
Hey @eduardovegap !  For tomorrow .... can you confirm it will be Electric Circus?

**Comment by jessicazartler** [comment] 2021-02-24 18:42
Also @eduardovegap I am confirming with Shermin/Token Kitchen whether she wants March 4 or 11 -- and we can have Dacade on whichever week she doesn't choose? If that is okay, she is quite full schedule so I thought we would let her choose first as Dacade is more flexible

**Comment by jessicazartler** [comment] 2021-02-26 21:51
@eduardovegap Shermin w/ Token Kitchen will present March 11 -- added also to the curate sheet

**Comment by tamarandom** [comment] 2021-03-01 08:47
@jessicazartler @eduardovegap Does that mean Dacade will be this week? Mar 4? I checked the xls but it's not in there. ;( Do we need someone for this week?

**Comment by jessicazartler** [comment] 2021-03-01 18:24
@eduardovegap can you confirm Dacade for this week? Thank you!

**Comment by eduardovegap** [comment] 2021-03-01 19:48
@jessicazartler @tamarandom I wrote them to confirm, waiting for reply.

**Comment by eduardovegap** [comment] 2021-03-01 21:43
@iviangita Dacade P2P confirmed.

**Comment by eduardovegap** [comment] 2021-03-01 21:52
quick question @jessicazartler are we using new discord for this calls?

**Comment by jessicazartler** [comment] 2021-03-02 00:05
We are talking about this tomorrow in Comms - should be will confirm tomorrow - we discussed starting in old and migrating together to new... tomorrow we'll decide

**Comment by markoprljic** [comment] 2021-03-02 05:18
> quick question @jessicazartler are we using new discord for this calls?

YES! Please :)

**Comment by tamarandom** [comment] 2021-03-04 13:54
Update : Done! The updates are in the body of issue!

**Comment by iviangita** [comment] 2021-03-17 07:25
Hi @eduardovegap @jessicazartler! Who will be the speaker this week Mar 18? :D

**Comment by jessicazartler** [comment] 2021-03-17 13:38
I forget, @eduardovegap did Dacade/Electric Circus go together or was Dacade still to go? I don't have anyone else lined up.. do you? Thank you so much for the reminder @iviangita!

**Comment by tamarandom** [comment] 2021-03-18 14:40
Done for this week! Let brainstorming for next week begin!

**Comment by tamarandom** [comment] 2021-03-23 17:44
Suggestion from the Comms call : the TEC Params presented by Vitor (pending confirmation)

**Comment by markoprljic** [comment] 2021-03-23 17:58
@marthendalnunes See above.

**Comment by freedumbs00** [comment] 2021-03-23 20:01
Yeah...  I can ask him too.

**Comment by iviangita** [comment] 2021-03-25 05:24
Has Vitor confirmed to present? :)

**Comment by tamarandom** [comment] 2021-03-25 06:11
There is a 90% chance. Let’s put it in the Agenda and we can take out last minute if not. The new Giveth.io is plan B.

**Comment by freedumbs00** [comment] 2021-03-25 15:53
Vitor is presenting.

**Comment by freedumbs00** [comment] 2021-03-25 15:54
closing issue

**Comment by tamarandom** [comment] 2021-03-30 18:20
Another week, another Thursday community call. ;) 

cadCAD EDU <-- can't do this week but another one, possibly. 
giveth.io <-- our last resort option.

**Comment by tamarandom** [comment] 2021-03-31 15:55
Hey @eduardovegap I'm going to close this issue as we moved to tracking it in the Community Stewards call. If we need to open another one later to have a single person drive it, we can. It might even make more sense to add it to the Hatch Outreach weekly since that's where we will have the most knowledge about the projects we are reaching out to!

**Closed by tamarandom** 2021-03-31 15:55 UTC
Labels: Communications WG
