### ISSUE TITLE
Soft Gov Trial Audit

### ISSUE THREAD

**Issue by Zeptimus** [TECommons/coordination#433] opened 2021-02-15 12:57 UTC
## 📋 Anything to add?

@iviangita and @Zeptimus will prepare the documentation and contact @liviade1 
Note: Add feedback on the comment section
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment] 2021-02-19 17:37
Dupe of #451

**Closed by tamarandom** 2021-02-19 17:37 UTC
Labels: Next sprint?, Transparency WG
