### ISSUE TITLE
CSTK holder transparency list (names & % holdings)

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#55] opened 2020-11-10 14:22 UTC
Task is tracked in Commons Stack's repo
https://github.com/commons-stack/iteration0/issues/9

**Comment by drllau** [comment] 2020-11-23 07:11
To be subject to Commons stack privacy [policy](https://commonsstack.org/privacypolicy) which includes opt-out .... first glance it seems to follow the notice & notice model of privacy notification. Note that CommonStack does not appear to be a self-regulatory org even though [minting tokens ](http://bankersacademy.com/resources/free-tutorials/57-ba-free-tutorials/609-aml-switzerland-sp-343)

>  We don't share any personally identifying information publicly or with third-parties, except when required to by law.

**Comment by tamarandom** [comment] 2020-11-25 18:52
Duplicate of #88

**Comment by tamarandom** [comment] 2021-01-03 13:20
This is a dupe of [commons-stack/iteration0/88](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/88)

**Closed by tamarandom** 2021-01-03 13:20 UTC
Labels: OnboardingWG
